sudo: false

language: scala

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: localhost

jdk:
  - oraclejdk8

scala:
  - "2.10.6"
  - "2.11.11"
  - "2.12.2"

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

script:
  - .travis/build.sh
